### ISSUE TITLE
codecvt missing in libstdc++

### ISSUE THREAD

**Issue by kuhar** [jeaye/jeayeson#10]
When compiling with gcc-4.9 and using libstdc++ following error occurs:
`In file included from include/jeayeson/detail/parser_util.hpp:20:
include/jeayeson/detail/utf.hpp:12:10: fatal error: 'codecvt' file not found
#include <codecvt>`

How about using boost equivalent?

**Comment by kuhar** [comment]
OK, I've just noticed this:

`NOTE: Due to the usage of C++11's <codecvt> for UTF-16 -> UTF-8 transcoding, the current GCC (4.9) is unable to compile JeayeSON. For now, I'm using clang while I consider alternatives.`

**Comment by jeaye** [comment]
Sorry for the hassle. I have fixed this issue now (your comment reminded me of it), so you should be able to compile with a modern GCC version (4.9.x works for me).
